import {supabase} from '../../lib/supabase';

function db(){if(!supabase)throw new Error('La plataforma aún no está configurada.');return supabase;}
function translate(code:string){const labels:Record<string,string>={INVALID_CREDENTIALS:'DNI o contraseña incorrectos.',ACCOUNT_TEMPORARILY_LOCKED:'Cuenta bloqueada por 15 minutos debido a varios intentos fallidos.',PORTAL_ACCOUNT_NOT_FOUND:'No existe una cuenta de portal activa.',INVALID_EMAIL:'El correo no es válido.',INVALID_PHONE:'El número de celular no es válido.',INVALID_ADDRESS:'La dirección es demasiado corta.',PHOTO_TOO_LARGE:'La fotografía supera 5 MB.',PHOTO_FORMAT_NOT_ALLOWED:'La fotografía debe ser JPG, PNG o WEBP.'};return labels[code]??code;}

export async function portalLogin(dni:string,password:string){const response=await db().functions.invoke('subscriber-portal-login',{body:{dni,password}});if(response.error)throw new Error(translate(response.error.message));if(response.data?.error)throw new Error(translate(response.data.error));return response.data as {access_token:string;refresh_token:string};}
export async function getPortalProfile(){const{data,error}=await db().functions.invoke('subscriber-portal-profile',{method:'GET'});if(error)throw new Error(translate(error.message));if(data?.error)throw new Error(translate(data.error));return data;}
export async function updatePortalProfile(payload:{whatsapp:string;email:string;address:string}){const{data,error}=await db().functions.invoke('subscriber-portal-profile',{method:'PUT',body:payload});if(error)throw new Error(translate(error.message));if(data?.error)throw new Error(translate(data.error));return data;}
export async function updatePortalPhoto(file:File){const form=new FormData();form.append('photo',file);const{data,error}=await db().functions.invoke('subscriber-portal-profile',{method:'POST',body:form});if(error)throw new Error(translate(error.message));if(data?.error)throw new Error(translate(data.error));return data;}
export async function createPortalAccess(subscriberId:string,temporaryPassword?:string){const{data,error}=await db().functions.invoke('admin-create-subscriber-portal',{body:{subscriber_id:subscriberId,temporary_password:temporaryPassword||undefined}});if(error)throw new Error(translate(error.message));if(data?.error)throw new Error(translate(data.error));return data as {temporary_password:string;dni_masked:string;subscriber_name:string};}
export async function changePortalPassword(password:string){if(password.length<10)throw new Error('La nueva contraseña debe tener al menos 10 caracteres.');const{error}=await db().auth.updateUser({password});if(error)throw new Error(error.message);const{error:markError}=await db().rpc('mark_my_portal_password_changed');if(markError)throw new Error(markError.message);}
