import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import type {Session,User} from '@supabase/supabase-js';
import {configured,supabase} from '../lib/supabase';import type {Permission} from '../lib/security';
type Profile={id:string;full_name:string;username:string;status:string;organization_id:string};
type AuthValue={configured:boolean;loading:boolean;session:Session|null;user:User|null;profile:Profile|null;permissions:Permission[];mfaVerified:boolean;hasVerifiedFactor:boolean;signIn:(email:string,password:string)=>Promise<void>;enrollMfa:()=>Promise<{factor:{id:string};qr:string;secret:string}>;verifyEnrollment:(factorId:string,code:string)=>Promise<void>;verifyMfa:(code:string)=>Promise<void>;signOut:()=>Promise<void>;has:(p:Permission)=>boolean};
const C=createContext<AuthValue|null>(null);
export function AuthProvider({children}:{children:ReactNode}){const[session,setSession]=useState<Session|null>(null);const[profile,setProfile]=useState<Profile|null>(null);const[permissions,setPermissions]=useState<Permission[]>([]);const[loading,setLoading]=useState(true);const[mfaVerified,setMfaVerified]=useState(false);const[hasVerifiedFactor,setHasVerifiedFactor]=useState(false);
 async function load(s:Session|null){setLoading(true);setSession(s);setProfile(null);setPermissions([]);setMfaVerified(false);setHasVerifiedFactor(false);if(!s||!supabase){setLoading(false);return;}const[{data,error},{data:factors},{data:aal}]=await Promise.all([supabase.rpc('get_my_authorization'),supabase.auth.mfa.listFactors(),supabase.auth.mfa.getAuthenticatorAssuranceLevel()]);if(error){setLoading(false);throw error;}setProfile(data?.profile??null);setPermissions(data?.permissions??[]);setHasVerifiedFactor(Boolean(factors?.totp.some(x=>x.status==='verified')));const verified=aal?.currentLevel==='aal2';setMfaVerified(verified);if(verified&&!sessionStorage.getItem(`audit-login-${s.access_token.slice(-12)}`)){await supabase.rpc('log_session_event',{p_action:'session.login',p_metadata:{user_agent:navigator.userAgent}});sessionStorage.setItem(`audit-login-${s.access_token.slice(-12)}`,'1');}setLoading(false);}
 useEffect(()=>{if(!supabase){setLoading(false);return;}supabase.auth.getSession().then(({data})=>load(data.session)).catch(()=>setLoading(false));const{data}=supabase.auth.onAuthStateChange((_e,s)=>{void load(s)});return()=>data.subscription.unsubscribe();},[]);
 async function signIn(email:string,password:string){if(!supabase)throw new Error('Configuración segura pendiente.');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw new Error('Usuario o contraseña incorrectos.');}
 async function enrollMfa(){if(!supabase)throw new Error('Configuración segura pendiente.');const{data,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'Junta de Agua'});if(error)throw new Error(error.message);return{factor:data,qr:data.totp.qr_code,secret:data.totp.secret};}
 async function verifyEnrollment(factorId:string,code:string){if(!supabase)throw new Error('Configuración segura pendiente.');const{data:c,error:ce}=await supabase.auth.mfa.challenge({factorId});if(ce)throw new Error('No se pudo iniciar la verificación.');const{error}=await supabase.auth.mfa.verify({factorId,challengeId:c.id,code});if(error)throw new Error('Código inválido.');await load((await supabase.auth.getSession()).data.session);}
 async function verifyMfa(code:string){if(!supabase)throw new Error('Configuración segura pendiente.');const{data:f}=await supabase.auth.mfa.listFactors();const factor=f?.totp.find(x=>x.status==='verified');if(!factor)throw new Error('No existe un factor configurado.');const{data:c,error:ce}=await supabase.auth.mfa.challenge({factorId:factor.id});if(ce)throw new Error('No se pudo iniciar la verificación.');const{error}=await supabase.auth.mfa.verify({factorId:factor.id,challengeId:c.id,code});if(error)throw new Error('Código de autenticación inválido.');await load((await supabase.auth.getSession()).data.session);}
 async function signOut(){if(supabase&&session){await supabase.rpc('log_session_event',{p_action:'session.logout',p_metadata:{user_agent:navigator.userAgent}});}await supabase?.auth.signOut();sessionStorage.clear();}
 const value={configured,loading,session,user:session?.user??null,profile,permissions,mfaVerified,hasVerifiedFactor,signIn,enrollMfa,verifyEnrollment,verifyMfa,signOut,has:(p:Permission)=>permissions.includes(p)};return <C.Provider value={value}>{children}</C.Provider>}
export function useAuth(){const v=useContext(C);if(!v)throw new Error('AuthProvider faltante');return v;}
