import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
async function context(req:Request){const url=Deno.env.get('SUPABASE_URL')!;const anon=Deno.env.get('SUPABASE_ANON_KEY')!;const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const caller=createClient(url,anon,{global:{headers:{Authorization:req.headers.get('Authorization')??''}}});const{data:auth}=await caller.auth.getUser();if(!auth.user)throw new Error('AUTH_REQUIRED');const{data:allowed}=await caller.rpc('has_permission',{p_code:'integrations.manage'});if(!allowed)throw new Error('FORBIDDEN');const{data:aal}=await caller.auth.mfa.getAuthenticatorAssuranceLevel();if(aal?.currentLevel!=='aal2')throw new Error('MFA_REQUIRED');const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const{data:profile}=await admin.from('profiles').select('organization_id').eq('id',auth.user.id).single();if(!profile)throw new Error('PROFILE_NOT_FOUND');return{admin,user:auth.user,organizationId:profile.organization_id};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const{admin,user,organizationId}=await context(req);const{key}=await req.json();let ok=false;let message='';let details:Record<string,unknown>={};
 if(key==='email'){const token=Deno.env.get('RESEND_API_KEY');if(!token)throw new Error('RESEND_API_KEY_NOT_CONFIGURED');const r=await fetch('https://api.resend.com/domains',{headers:{Authorization:`Bearer ${token}`}});ok=r.ok;message=ok?'Resend respondió correctamente.':`Resend respondió ${r.status}.`;}
 else if(key==='whatsapp'){const token=Deno.env.get('WHATSAPP_ACCESS_TOKEN');const phoneId=Deno.env.get('WHATSAPP_PHONE_NUMBER_ID');if(!token||!phoneId)throw new Error('WHATSAPP_SECRETS_NOT_CONFIGURED');const r=await fetch(`https://graph.facebook.com/v23.0/${phoneId}?fields=display_phone_number,verified_name`,{headers:{Authorization:`Bearer ${token}`}});const j=await r.json();ok=r.ok;message=ok?'WhatsApp Cloud API respondió correctamente.':String(j?.error?.message??`HTTP ${r.status}`);details=ok?j:{};}
 else if(key==='ocr'){const apiKey=Deno.env.get('GOOGLE_VISION_API_KEY');if(!apiKey)throw new Error('GOOGLE_VISION_API_KEY_NOT_CONFIGURED');const pixel='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';const r=await fetch(`https://vision.googleapis.com/v1/images:annotate?key=${apiKey}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requests:[{image:{content:pixel},features:[{type:'TEXT_DETECTION'}]}]})});ok=r.ok;message=ok?'Google Vision respondió correctamente.':`Google Vision respondió ${r.status}.`;}
 else if(key==='backup'){const{error}=await admin.storage.from('system-backups').list(organizationId,{limit:1});ok=!error;message=ok?'El almacenamiento privado de respaldos está disponible.':error!.message;}
 else if(key==='google_maps'){ok=Boolean(Deno.env.get('GOOGLE_MAPS_API_KEY_CONFIGURED')==='true');message=ok?'La clave del mapa está declarada como configurada. Verifique además la carga desde Render.':'Configure VITE_GOOGLE_MAPS_API_KEY en Render y GOOGLE_MAPS_API_KEY_CONFIGURED=true en Supabase.';}
 else throw new Error('INVALID_INTEGRATION');
 await admin.from('integrations').upsert({organization_id:organizationId,key,enabled:ok,secret_configured:ok,last_checked_at:new Date().toISOString(),last_error:ok?null:message,updated_by:user.id},{onConflict:'organization_id,key'});
 return new Response(JSON.stringify({ok,message,details}),{headers:{...cors,'Content-Type':'application/json'}});
 }catch(e){return new Response(JSON.stringify({ok:false,message:e instanceof Error?e.message:'UNKNOWN_ERROR'}),{status:400,headers:{...cors,'Content-Type':'application/json'}})}});
