import {jsPDF} from 'jspdf';
import QRCode from 'qrcode';
export type ReceiptBrand={name?:string;address?:string;phone?:string;rtn?:string;footer?:string;logoDataUrl?:string};
export async function createReceiptPdfBlob(receipt:{number:string;subscriber:string;subscriberCode?:string;date:string;total:number;received:number;change:number;method:string;items:{description:string;amount:number}[];verification?:string;brand?:ReceiptBrand;copy?:boolean}){const pdf=new jsPDF();const b=receipt.brand??{};if(receipt.copy){pdf.setTextColor(185,185,185);pdf.setFontSize(38);pdf.text('COPIA',105,150,{align:'center',angle:35});pdf.setTextColor(0,0,0);}if(b.logoDataUrl){try{pdf.addImage(b.logoDataUrl,'PNG',20,12,24,24)}catch{/* El recibo sigue siendo válido sin imagen si el formato no es compatible. */}}pdf.setFontSize(16);pdf.text(b.name||'Junta de Agua',50,20);pdf.setFontSize(9);if(b.rtn)pdf.text(`RTN: ${b.rtn}`,50,27);if(b.address)pdf.text(b.address,50,33);if(b.phone)pdf.text(`Teléfono: ${b.phone}`,50,39);pdf.line(20,45,190,45);pdf.setFontSize(11);pdf.text(`Recibo: ${receipt.number}`,20,54);pdf.text(`Abonado: ${receipt.subscriber}${receipt.subscriberCode?` (${receipt.subscriberCode})`:''}`,20,61);pdf.text(`Fecha: ${receipt.date}`,20,68);pdf.text(`Forma de pago: ${receipt.method}`,20,75);let y=87;receipt.items.forEach(i=>{const lines=pdf.splitTextToSize(i.description,115);pdf.text(lines,20,y);pdf.text(`L ${i.amount.toFixed(2)}`,180,y,{align:'right'});y+=Math.max(7,lines.length*5);});pdf.line(20,y,190,y);y+=8;pdf.text(`Total: L ${receipt.total.toFixed(2)}`,180,y,{align:'right'});y+=7;pdf.text(`Recibido: L ${receipt.received.toFixed(2)}`,180,y,{align:'right'});y+=7;pdf.text(`Cambio: L ${receipt.change.toFixed(2)}`,180,y,{align:'right'});if(receipt.verification){const qr=await QRCode.toDataURL(receipt.verification);pdf.addImage(qr,'PNG',20,y+4,28,28);pdf.setFontSize(8);pdf.text('Verifique la autenticidad escaneando el código QR.',52,y+16);}if(b.footer){pdf.setFontSize(8);pdf.text(pdf.splitTextToSize(b.footer,165),20,280);}return pdf.output('blob');}
export async function downloadReceiptPdf(receipt:Parameters<typeof createReceiptPdfBlob>[0]){const blob=await createReceiptPdfBlob(receipt);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${receipt.number}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return blob;}
function esc(v:unknown){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function sheet(name:string,headers:string[],rows:(string|number)[][]){const cells=(r:(string|number)[])=>`<Row>${r.map(v=>`<Cell><Data ss:Type="${typeof v==='number'?'Number':'String'}">${esc(v)}</Data></Cell>`).join('')}</Row>`;return `<Worksheet ss:Name="${esc(name).slice(0,31)}"><Table>${cells(headers)}${rows.map(cells).join('')}</Table></Worksheet>`;}
export function downloadWorkbookXml(filename:string,sheets:{name:string;headers:string[];rows:(string|number)[][]}[]){const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${sheets.map(x=>sheet(x.name,x.headers,x.rows)).join('')}</Workbook>`;const url=URL.createObjectURL(new Blob([xml],{type:'application/vnd.ms-excel'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function downloadExcelXml(filename:string,headers:string[],rows:(string|number)[][]){downloadWorkbookXml(filename,[{name:'Informe',headers,rows}]);}
