import { supabase } from '../../lib/supabase';
function db(){if(!supabase)throw new Error('La base segura aún no está configurada.');return supabase;}
function fail(e:{message:string}|null){if(e)throw new Error(e.message);}
export async function searchPayableAccounts(q:string){const {data,error}=await db().rpc('search_payable_accounts',{p_query:q,p_limit:50});fail(error);return data??[];}
export async function openCashSession(input:{opening_amount:number;location?:string}){const {data,error}=await db().rpc('open_cash_session',{p_opening_amount:input.opening_amount,p_location:input.location??null});fail(error);return data;}
export async function getActiveCashSession(){const {data,error}=await db().rpc('get_active_cash_session');fail(error);return data;}
export async function registerPayment(input:{subscriber_id:string;cash_session_id?:string;method:string;received_amount:number;reference?:string;components?:{method:'cash'|'transfer'|'deposit'|'check';amount:number;reference?:string}[];allocations:{obligation_id:string;amount:number}[]}){const {data,error}=await db().rpc('register_payment',{p_payload:input});fail(error);return data;}
export async function closeCashSession(input:{session_id:string;counted_amount:number;notes?:string}){const {data,error}=await db().rpc('close_cash_session',{p_session_id:input.session_id,p_counted_amount:input.counted_amount,p_notes:input.notes??null});fail(error);return data;}
export async function voidPayment(input:{payment_id:string;reason:string}){const {data,error}=await db().rpc('void_payment',{p_payment_id:input.payment_id,p_reason:input.reason});fail(error);return data;}
export async function refundPayment(input:{payment_id:string;amount:number;reason:string}){const {data,error}=await db().rpc('refund_payment',{p_payment_id:input.payment_id,p_amount:input.amount,p_reason:input.reason});fail(error);return data;}
export async function listPayments(limit=100){const {data,error}=await db().rpc('list_payments',{p_limit:limit});fail(error);return data??[];}
export async function listExpenses(){const {data,error}=await db().rpc('list_expenses');fail(error);return data??[];}
export async function createExpenseRequest(input:Record<string,unknown>){const {data,error}=await db().rpc('create_expense_request',{p_payload:input});fail(error);return data;}
export async function approveExpense(id:string,decision:'approved'|'rejected',notes?:string){const {data,error}=await db().rpc('approve_expense',{p_expense_id:id,p_decision:decision,p_notes:notes??null});fail(error);return data;}
export async function confirmExpense(input:{expense_id:string;invoice_path:string;invoice_number:string;paid_from:string}){const {data,error}=await db().rpc('confirm_expense',{p_expense_id:input.expense_id,p_invoice_path:input.invoice_path,p_invoice_number:input.invoice_number,p_paid_from:input.paid_from});fail(error);return data;}
export async function uploadExpenseEvidence(file:File,expenseId:string){const {data:auth}=await db().auth.getUser();const {data:profile,error:pe}=await db().from('profiles').select('organization_id').eq('id',auth.user?.id??'').single();fail(pe);if(!profile)throw new Error('No se pudo determinar la organización.');const path=`${profile.organization_id}/${expenseId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await db().storage.from('expense-evidence').upload(path,file,{upsert:false});fail(error);return path;}
export async function getFinancialDashboard(from:string,to:string){const {data,error}=await db().rpc('get_financial_dashboard',{p_from:from,p_to:to});fail(error);return data;}
export async function getTransparencyReport(year:number){const {data,error}=await db().rpc('get_transparency_report',{p_year:year});fail(error);return data;}
export async function getExpenseEvidenceUrl(path:string){const {data,error}=await db().storage.from('expense-evidence').createSignedUrl(path,300);fail(error);return data?.signedUrl??'';}

export async function uploadPaymentReceipt(paymentId:string,receiptNumber:string,blob:Blob){const {data:auth}=await db().auth.getUser();const {data:profile,error:pe}=await db().from('profiles').select('organization_id').eq('id',auth.user?.id??'').single();fail(pe);if(!profile)throw new Error('No se pudo determinar la organización.');const path=`${profile.organization_id}/${new Date().getFullYear()}/${paymentId}/${receiptNumber}.pdf`;const {error}=await db().storage.from('receipt-documents').upload(path,blob,{contentType:'application/pdf',upsert:true});fail(error);const {error:ae}=await db().rpc('attach_payment_receipt',{p_payment_id:paymentId,p_storage_path:path});fail(ae);return path;}
export async function getPaymentReceiptUrl(path:string){const {data,error}=await db().storage.from('receipt-documents').createSignedUrl(path,600);fail(error);return data?.signedUrl??'';}

export async function getPaymentReceiptData(paymentId:string){const{data,error}=await db().rpc('get_payment_receipt_data',{p_payment_id:paymentId});fail(error);return data;}
export async function recordPaymentReprint(paymentId:string){const{error}=await db().rpc('record_payment_reprint',{p_payment_id:paymentId});fail(error);}
