import { useEffect,useState } from 'react';
import { AlertTriangle,CheckCircle2,Search,WalletCards } from 'lucide-react';
import { authorizeDebtOverride,checkDebtOperation,createManualObligation,getSubscriberAccount,listTariffs,searchAccounts } from '../features/billing/service';
import { useAuth } from '../contexts/AuthContext';
const money=(value:unknown)=>new Intl.NumberFormat('es-HN',{style:'currency',currency:'HNL'}).format(Number(value??0));
const labels:Record<string,string>={pending:'Pendiente',partial:'Parcial',paid:'Pagada',overdue:'Vencida',cancelled:'Cancelada'};
export function Accounts(){const auth=useAuth();const [query,setQuery]=useState('');const [rows,setRows]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [tariffs,setTariffs]=useState<any[]>([]);const [message,setMessage]=useState('');const [operation,setOperation]=useState('solvency_certificate');const [operationResult,setOperationResult]=useState<any>(null);const [manual,setManual]=useState({connection_id:'',tariff_definition_id:'',due_date:'',description:''});const [overrideReason,setOverrideReason]=useState('');
async function load(q=''){try{setRows(await searchAccounts(q));setTariffs(await listTariffs())}catch(e){setMessage(e instanceof Error?e.message:'No se pudieron consultar los estados de cuenta.')}}useEffect(()=>{void load()},[]);
async function open(id:string){try{setSelected(await getSubscriberAccount(id));setOperationResult(null)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo abrir el estado de cuenta.')}}
async function refresh(){if(selected?.subscriber?.id)setSelected(await getSubscriberAccount(selected.subscriber.id));await load(query)}
async function verify(){if(!selected?.subscriber?.id)return;try{setOperationResult(await checkDebtOperation(selected.subscriber.id,operation))}catch(e){setMessage(e instanceof Error?e.message:'No se pudo validar la operación.')}}
async function addManual(){if(!selected?.subscriber?.id||!manual.tariff_definition_id||!manual.due_date){setMessage('Seleccione tarifa y fecha de vencimiento.');return;}try{await createManualObligation({subscriber_id:selected.subscriber.id,...manual});setMessage('Obligación registrada y reflejada en el estado de cuenta.');setManual({connection_id:'',tariff_definition_id:'',due_date:'',description:''});await refresh()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo crear la obligación.')}}
async function override(){if(!selected?.subscriber?.id||overrideReason.trim().length<20){setMessage('La justificación debe tener al menos 20 caracteres.');return;}try{await authorizeDebtOverride({subscriber_id:selected.subscriber.id,operation,reason:overrideReason});setMessage('Excepción autorizada y registrada en auditoría.');setOverrideReason('')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo autorizar la excepción.')}}
return <main className="content"><div className="titlebar"><div><h1>Estados de cuenta y morosidad</h1><p>Obligaciones, vencimientos, saldos y bloqueos operativos calculados por el servidor.</p></div></div><div className="search"><Search size={18}/><input placeholder="Código o nombre del abonado" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load(query)}}/><button onClick={()=>void load(query)}>Buscar</button></div>{message&&<div className={message.includes('correctamente')||message.includes('registrada')||message.includes('autorizada')?'notice':'error'}>{message}</div>}<div className="subscriber-layout"><section className="panel"><table><thead><tr><th>Código</th><th>Abonado</th><th>Pendiente</th><th>Vencido</th><th>Estado</th></tr></thead><tbody>{rows.map(r=><tr key={r.subscriber_id} onClick={()=>void open(r.subscriber_id)}><td>{r.subscriber_code}</td><td>{r.full_name}</td><td>{money(r.total_pending)}</td><td>{money(r.overdue_amount)}</td><td><span className={`pill ${r.debt_status==='moroso'?'danger':''}`}>{r.debt_status}</span></td></tr>)}</tbody></table>{rows.length===0&&<p className="empty">No hay resultados.</p>}</section><section className="panel detail">{selected?<><div className="titlebar"><div><h2>{selected.subscriber.code} · {selected.subscriber.full_name}</h2><p>Estado de cuenta consolidado</p></div>{selected.summary.solvent?<CheckCircle2 className="ok"/>:<AlertTriangle className="warn"/>}</div><div className="stats"><div><small>Total pendiente</small><strong>{money(selected.summary.total_pending)}</strong></div><div><small>Total vencido</small><strong>{money(selected.summary.overdue_amount)}</strong></div><div><small>Días de mora</small><strong>{selected.summary.days_overdue}</strong></div></div><h3>Obligaciones</h3><div className="table-scroll"><table><thead><tr><th>Periodo</th><th>Concepto</th><th>Pegue</th><th>Vence</th><th>Original</th><th>Saldo</th><th>Estado</th></tr></thead><tbody>{selected.obligations.map((o:any)=><tr key={o.id}><td>{o.period_key}</td><td>{o.description}</td><td>{o.connection_code||'General'}</td><td>{o.due_date}</td><td>{money(o.original_amount)}</td><td>{money(o.balance)}</td><td><span className={`pill ${o.computed_state==='overdue'?'danger':''}`}>{labels[o.computed_state]??o.computed_state}</span></td></tr>)}</tbody></table></div>
{auth.has('obligations.manage')&&<><h3>Agregar obligación</h3><div className="inline-form"><select value={manual.tariff_definition_id} onChange={e=>setManual({...manual,tariff_definition_id:e.target.value})}><option value="">Seleccione tarifa</option>{tariffs.filter(t=>t.status==='active').map(t=><option key={t.definition_id} value={t.definition_id}>{t.code} · {t.name} · {money(t.amount)}</option>)}</select><select value={manual.connection_id} onChange={e=>setManual({...manual,connection_id:e.target.value})}><option value="">Obligación general</option>{selected.connections.map((c:any)=><option key={c.id} value={c.id}>{c.code} · {c.address}</option>)}</select><input type="date" value={manual.due_date} onChange={e=>setManual({...manual,due_date:e.target.value})}/><input placeholder="Descripción opcional" value={manual.description} onChange={e=>setManual({...manual,description:e.target.value})}/><button onClick={()=>void addManual()}>Registrar</button></div></>}
<h3>Validar operación</h3><div className="inline-form"><select value={operation} onChange={e=>setOperation(e.target.value)}><option value="solvency_certificate">Constancia de solvencia</option><option value="reconnection">Reconexión</option><option value="ownership_change">Cambio de propietario</option><option value="new_connection">Nuevo pegue</option><option value="receive_payment">Recibir pago</option><option value="general_consultation">Consulta general</option></select><button onClick={()=>void verify()}>Comprobar</button></div>{operationResult&&<div className={operationResult.blocked?'error':'notice'}><strong>{operationResult.blocked?'Operación bloqueada':'Operación permitida'}</strong><p>{operationResult.reason||'La deuda no impide esta operación.'}</p><p>Vencido: {money(operationResult.overdue_amount)} · Pendiente total: {money(operationResult.total_pending)}</p>{operationResult.blocked&&auth.has('debt.override')&&<div><textarea value={overrideReason} onChange={e=>setOverrideReason(e.target.value)} placeholder="Justificación excepcional, mínimo 20 caracteres"/><button onClick={()=>void override()}>Autorizar excepción con MFA</button></div>}</div>}</>:<div className="empty"><WalletCards size={40}/><p>Seleccione un abonado para consultar su estado de cuenta.</p></div>}</section></div></main>}
