import {useCallback,useEffect,useRef,useState} from 'react';import {FileCheck2,Plus} from 'lucide-react';import {approveExpense,confirmExpense,createExpenseRequest,getExpenseEvidenceUrl,listExpenses,uploadExpenseEvidence} from '../features/finance/service';import {useAuth} from '../contexts/AuthContext';
type Row=Record<string,any>;
export function Expenses(){const auth=useAuth();const[rows,setRows]=useState<Row[]>([]);const[error,setError]=useState('');const[message,setMessage]=useState('');const[fileTarget,setFileTarget]=useState<Row|null>(null);const fileRef=useRef<HTMLInputElement>(null);const[form,setForm]=useState({description:'',reason:'',category:'Tuberías y accesorios',supplier:'',amount:''});
 const load=useCallback(async()=>{try{setRows(await listExpenses());setError('')}catch(e){setError((e as Error).message)}},[]);useEffect(()=>{void load()},[load]);
 async function create(e:React.FormEvent){e.preventDefault();try{await createExpenseRequest({...form,amount:Number(form.amount)});setForm({description:'',reason:'',category:'Tuberías y accesorios',supplier:'',amount:''});setMessage('Solicitud registrada.');await load()}catch(err){setError((err as Error).message)}}
 async function upload(file:File){if(!fileTarget)return;try{const path=await uploadExpenseEvidence(file,fileTarget.id);const invoice=(document.getElementById(`invoice-${fileTarget.id}`) as HTMLInputElement)?.value.trim();const paid=(document.getElementById(`paid-${fileTarget.id}`) as HTMLSelectElement)?.value;if(!invoice)throw new Error('El número de factura es obligatorio.');await confirmExpense({expense_id:fileTarget.id,invoice_path:path,invoice_number:invoice,paid_from:paid||'cash'});setMessage('Gasto comprobado y contabilizado.');setFileTarget(null);await load()}catch(err){setError((err as Error).message)}}
 return <main className="content"><div className="titlebar"><div><h1>Gastos y balance</h1><p>Ninguna salida se contabiliza sin aprobación separada y factura.</p></div></div>{error&&<div className="error">{error}</div>}{message&&<div className="notice">{message}</div>}
 {auth.has('expenses.create')&&<section className="panel"><h2><Plus/> Solicitar gasto</h2><form className="form-grid" onSubmit={create}><label>Descripción<input required minLength={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Motivo<input required minLength={3} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><label>Categoría<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Tuberías y accesorios</option><option>Mantenimiento</option><option>Electricidad</option><option>Combustible</option><option>Mano de obra</option><option>Papelería</option><option>Otros</option></select></label><label>Proveedor<input value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})}/></label><label>Monto<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><div><button>Registrar solicitud</button></div></form></section>}
 <section className="panel" style={{marginTop:'1rem'}}><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Descripción</th><th>Motivo</th><th>Categoría</th><th>Proveedor</th><th>Monto</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleDateString('es-HN')}</td><td>{r.description}</td><td>{r.reason}</td><td>{r.category}</td><td>{r.supplier||'—'}</td><td>L {Number(r.amount).toFixed(2)}</td><td>{r.status}</td><td>{r.status==='requested'&&auth.has('expenses.approve')&&<><button className="compact" onClick={async()=>{await approveExpense(r.id,'approved');await load()}}>Aprobar</button><button className="compact outline" onClick={async()=>{await approveExpense(r.id,'rejected');await load()}}>Rechazar</button></>}{r.status==='approved'&&auth.has('expenses.confirm')&&<div className="subform"><input id={`invoice-${r.id}`} placeholder="Número de factura"/><select id={`paid-${r.id}`}><option value="cash">Efectivo</option><option value="bank">Banco</option><option value="transfer">Transferencia</option></select><button className="compact" onClick={()=>{setFileTarget(r);fileRef.current?.click()}}><FileCheck2/>Adjuntar y contabilizar</button></div>}{r.invoice_path&&<button className="compact outline" onClick={async()=>{const url=await getExpenseEvidenceUrl(r.invoice_path);window.open(url,'_blank','noopener,noreferrer')}}>Ver factura</button>}</td></tr>)}</tbody></table></div></section><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value=''}}/></main>}
