import {useCallback,useEffect,useState} from 'react';import {MapPin,MessageCircle,ScanText,Mail,Cloud,RefreshCw} from 'lucide-react';import {listIntegrations,saveIntegration,testIntegration} from '../features/integrations/service';
const catalog=[
 {key:'google_maps',name:'Google Maps',icon:MapPin,desc:'Mapa interactivo y ubicación de pegues.',secret:'Render: VITE_GOOGLE_MAPS_API_KEY y VITE_GOOGLE_MAPS_MAP_ID',fields:[['default_center','Centro predeterminado','14.7692,-87.9900']]},
 {key:'ocr',name:'OCR documental',icon:ScanText,desc:'Lectura de DNI, pasaporte y facturas en imagen.',secret:'Supabase Secret: GOOGLE_VISION_API_KEY',fields:[['provider','Proveedor','google_vision']]},
 {key:'whatsapp',name:'WhatsApp Cloud API',icon:MessageCircle,desc:'Mensajes, documentos y estados de entrega.',secret:'Supabase Secrets: WHATSAPP_ACCESS_TOKEN, WHATSAPP_PHONE_NUMBER_ID, WHATSAPP_VERIFY_TOKEN',fields:[['country_code','Código de país','504']]},
 {key:'email',name:'Correo transaccional',icon:Mail,desc:'Recibos, informes e invitaciones.',secret:'Supabase Secrets: RESEND_API_KEY y EMAIL_FROM',fields:[['reply_to','Correo de respuesta','']]},
 {key:'backup',name:'Respaldo externo',icon:Cloud,desc:'Copias privadas, checksum y restauración.',secret:'Usa SUPABASE_SERVICE_ROLE_KEY y bucket privado system-backups',fields:[['retention_days','Retención en días','90']]}
];
export function Integrations(){const[rows,setRows]=useState<any[]>([]);const[forms,setForms]=useState<Record<string,Record<string,string>>>({});const[error,setError]=useState('');const[message,setMessage]=useState('');const load=useCallback(async()=>{try{const x=await listIntegrations();setRows(x);const next:Record<string,Record<string,string>>={};for(const c of catalog){const row=x.find((r:any)=>r.key===c.key);next[c.key]={};for(const[f,,d]of c.fields)next[c.key][f]=String(row?.public_config?.[f]??d);}setForms(next);setError('')}catch(e){setError((e as Error).message)}},[]);useEffect(()=>{void load()},[load]);return <main className="content"><div className="titlebar"><div><h1>Integraciones</h1><p>Configuración pública, secretos privados y pruebas reales de conexión.</p></div></div>{error&&<div className="error">{error}</div>}{message&&<div className="notice">{message}</div>}<div className="grid integration-grid">{catalog.map(c=>{const row=rows.find(r=>r.key===c.key);const Icon=c.icon;return <section className="panel" key={c.key}><div className="integration-head"><Icon/><div><h2>{c.name}</h2><p>{c.desc}</p></div></div><span className={`pill ${row?.enabled?'':'danger'}`}>{row?.enabled?'Conectada':'Pendiente'}</span><p className="help">Última verificación: {row?.last_checked_at?new Date(row.last_checked_at).toLocaleString('es-HN'):'Sin ejecutar'}</p>{row?.last_error&&<div className="error">{row.last_error}</div>}<div className="subform">{c.fields.map(([field,label])=><label key={field}>{label}<input value={forms[c.key]?.[field]??''} onChange={e=>setForms({...forms,[c.key]:{...(forms[c.key]??{}),[field]:e.target.value}})}/></label>)}</div><p className="secret-note"><strong>Configuración privada:</strong> {c.secret}</p><div className="actions"><button className="outline" onClick={async()=>{try{await saveIntegration(c.key,forms[c.key]??{},Boolean(row?.enabled));setMessage(`${c.name}: configuración pública guardada.`);await load()}catch(e){setError((e as Error).message)}}}>Guardar</button><button onClick={async()=>{try{setMessage(`Probando ${c.name}…`);const r=await testIntegration(c.key);setMessage(r.message);await load()}catch(e){setError((e as Error).message)}}}><RefreshCw size={16}/>Probar conexión</button></div></section>})}</div><div className="notice">Los tokens y claves privadas se configuran en Supabase Secrets. Esta pantalla nunca solicita ni devuelve secretos permanentes.</div></main>}
