import {useCallback,useEffect,useMemo,useState} from 'react';
import {Ban,Banknote,CheckCircle2,FileDown,Mail,ReceiptText,RotateCcw,Search,ShieldCheck,WalletCards,X} from 'lucide-react';
import {closeCashSession,getActiveCashSession,listPayments,openCashSession,refundPayment,registerPayment,searchPayableAccounts,uploadPaymentReceipt,voidPayment,getPaymentReceiptData,recordPaymentReprint} from '../features/finance/service';
import {createReceiptPdfBlob,downloadReceiptPdf,toReceiptBrandSnapshot,type ReceiptBrand,type ReceiptInput} from '../features/finance/documents';
import {sendEmail} from '../features/communications/service';
import {getOrganizationAssetUrl,getOrganizationSettings} from '../features/settings/service';
import {useAuth} from '../contexts/AuthContext';

type Row=Record<string,any>;
type PaymentComponent={method:'cash'|'transfer'|'deposit'|'check';amount:number;reference?:string};
const money=(value:unknown)=>new Intl.NumberFormat('es-HN',{style:'currency',currency:'HNL'}).format(Number(value??0));
const methodLabels:Record<string,string>={cash:'Efectivo',transfer:'Transferencia',deposit:'Depósito',check:'Cheque',mixed:'Mixto'};

async function assetDataUrl(path?:string|null){
  if(!path)return'';
  const url=await getOrganizationAssetUrl(path);if(!url)return'';
  const blob=await fetch(url).then(response=>response.blob());
  return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob)});
}

export function Payments(){
 const auth=useAuth();
 const[q,setQ]=useState('');const[results,setResults]=useState<Row[]>([]);const[selected,setSelected]=useState<Row|null>(null);const[chosen,setChosen]=useState<Record<string,boolean>>({});const[session,setSession]=useState<Row|null>(null);const[payments,setPayments]=useState<Row[]>([]);
 const[openingAmount,setOpeningAmount]=useState(0);const[cashLocation,setCashLocation]=useState('');const[countedAmount,setCountedAmount]=useState<number|''>('');
 const[received,setReceived]=useState(0);const[method,setMethod]=useState<'cash'|'transfer'|'deposit'|'check'|'mixed'>('cash');const[reference,setReference]=useState('');const[cashAmount,setCashAmount]=useState(0);const[secondaryMethod,setSecondaryMethod]=useState<'transfer'|'deposit'|'check'>('transfer');const[secondaryReference,setSecondaryReference]=useState('');
 const[error,setError]=useState('');const[message,setMessage]=useState('');const[brand,setBrand]=useState<ReceiptBrand>({templateVersion:'2.0'});const[action,setAction]=useState<{type:'void'|'refund';payment:Row}|null>(null);const[actionReason,setActionReason]=useState('');const[refundAmount,setRefundAmount]=useState(0);

 const resolveBrand=useCallback(async(snapshot?:ReceiptBrand|null):Promise<ReceiptBrand>=>{const source=snapshot&&Object.keys(snapshot).length?{...brand,...snapshot}:brand;const[logoDataUrl,signatureDataUrl,stampDataUrl]=await Promise.all([assetDataUrl(source.logoPath),assetDataUrl(source.signaturePath),assetDataUrl(source.stampPath)]);return{...source,logoDataUrl,signatureDataUrl,stampDataUrl}},[brand]);
 const load=useCallback(async()=>{try{setSession(await getActiveCashSession());setPayments(await listPayments());const settings=await getOrganizationSettings();const next:ReceiptBrand={name:settings?.name,address:settings?.address,phone:settings?.phone,email:settings?.email,rtn:settings?.rtn,footer:settings?.receipt_footer,logoPath:settings?.logo_path,signaturePath:settings?.signature_path,stampPath:settings?.stamp_path,signatoryName:settings?.receipt_signatory_name,signatoryTitle:settings?.receipt_signatory_title,templateVersion:settings?.receipt_template_version??'2.0'};const[logoDataUrl,signatureDataUrl,stampDataUrl]=await Promise.all([assetDataUrl(next.logoPath),assetDataUrl(next.signaturePath),assetDataUrl(next.stampPath)]);setBrand({...next,logoDataUrl,signatureDataUrl,stampDataUrl});setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{void load()},[load]);

 const allocations=useMemo(()=>(selected?.obligations??[]).filter((obligation:Row)=>chosen[obligation.id]).map((obligation:Row)=>({obligation_id:obligation.id,amount:Number(obligation.balance)})),[selected,chosen]);
 const total=allocations.reduce((sum:number,item:{amount:number})=>sum+item.amount,0);const secondaryAmount=Math.max(0,total-cashAmount);
 const components=useMemo<PaymentComponent[]>(()=>{if(method==='mixed')return[{method:'cash',amount:cashAmount},{method:secondaryMethod,amount:secondaryAmount,reference:secondaryReference}].filter(item=>item.amount>0) as PaymentComponent[];return[{method,amount:total,reference:method==='cash'?undefined:reference}] as PaymentComponent[]},[method,cashAmount,secondaryMethod,secondaryAmount,secondaryReference,total,reference]);
 const requiresCash=method==='cash'||method==='mixed';const effectiveReceived=requiresCash?received:total;const invalidMixed=method==='mixed'&&(cashAmount<=0||cashAmount>=total||!secondaryReference.trim());
 const canConfirm=allocations.length>0&&(!requiresCash||Boolean(session))&&effectiveReceived>=total&&(method==='cash'||method==='mixed'||reference.trim().length>0)&&!invalidMixed;

 async function search(){try{setResults(await searchPayableAccounts(q));setError('')}catch(e){setError((e as Error).message)}}
 async function pay(){if(!selected)return;try{const result=await registerPayment({subscriber_id:selected.id,cash_session_id:session?.id,method,received_amount:effectiveReceived,reference,components,allocations});const verification=`${window.location.origin}${result.verification_url}`;const receipt:ReceiptInput={number:result.receipt_number,subscriber:selected.full_name,subscriberCode:selected.code,date:new Date().toLocaleString('es-HN'),total,received:effectiveReceived,change:Math.max(0,effectiveReceived-total),method,items:(selected.obligations??[]).filter((obligation:Row)=>chosen[obligation.id]).map((obligation:Row)=>({description:obligation.description,amount:Number(obligation.balance)})),verification,brand,status:'confirmed',cashier:auth.profile?.full_name};const blob=await createReceiptPdfBlob(receipt);await uploadPaymentReceipt(result.id,result.receipt_number,blob,toReceiptBrandSnapshot(brand) as Record<string,unknown>);await downloadReceiptPdf(receipt);setMessage(`Pago contabilizado y recibo protegido: ${result.receipt_number}`);setSelected(null);setChosen({});setReceived(0);setReference('');setCashAmount(0);setSecondaryReference('');await load()}catch(e){setError((e as Error).message)}}
 async function open(){try{await openCashSession({opening_amount:openingAmount,location:cashLocation});setOpeningAmount(0);setCashLocation('');setMessage('Caja abierta correctamente.');await load()}catch(e){setError((e as Error).message)}}
 async function close(){if(!session||countedAmount==='')return;try{await closeCashSession({session_id:session.id,counted_amount:Number(countedAmount)});setCountedAmount('');setMessage('Caja cerrada y conciliada.');await load()}catch(e){setError((e as Error).message)}}
 async function emailReceipt(payment:Row){if(!payment.subscriber_email){setError('El abonado no tiene correo registrado.');return;}try{await sendEmail({to:payment.subscriber_email,subject:`Recibo ${payment.receipt_number}`,html:`<p>Adjuntamos su recibo institucional <strong>${payment.receipt_number}</strong> por ${money(payment.total)}.</p><p>Puede verificarlo en ${window.location.origin}/verificar-recibo/${payment.verification_token}</p>`,payment_id:payment.id,receipt_path:payment.receipt_path,filename:`${payment.receipt_number}.pdf`});setMessage('Recibo enviado por correo.')}catch(e){setError((e as Error).message)}}
 async function reprintReceipt(payment:Row){try{const data=await getPaymentReceiptData(payment.id);const historicalBrand=await resolveBrand((data.brand_snapshot??null) as ReceiptBrand|null);const verification=`${window.location.origin}/verificar-recibo/${data.verification_token}`;const receipt:ReceiptInput={number:data.receipt_number,subscriber:data.subscriber_name,subscriberCode:data.subscriber_code,date:new Date(data.created_at).toLocaleString('es-HN'),total:Number(data.total),received:Number(data.received_amount),change:Number(data.change_amount),method:data.method,items:(data.items??[]).map((item:Row)=>({description:item.description,amount:Number(item.amount)})),verification,brand:historicalBrand,copy:true,status:data.status,cashier:auth.profile?.full_name};await recordPaymentReprint(payment.id);await downloadReceiptPdf(receipt);setMessage('Reimpresión institucional generada y registrada en auditoría.')}catch(e){setError((e as Error).message)}}
 async function confirmAction(){if(!action)return;try{if(action.type==='void')await voidPayment({payment_id:action.payment.id,reason:actionReason});else await refundPayment({payment_id:action.payment.id,amount:refundAmount,reason:actionReason});setMessage(action.type==='void'?'Pago anulado mediante documento de reverso.':'Devolución registrada y saldo reabierto.');setAction(null);setActionReason('');setRefundAmount(0);await load()}catch(e){setError((e as Error).message)}}

 return <main className="content payments-page">
  <div className="titlebar module-hero"><div><span className="eyebrow">Tesorería y caja</span><h1>Pagos, recibos y contabilización</h1><p>Flujo controlado desde la selección de deuda hasta el recibo, auditoría y reverso.</p></div><span className="status-badge approved"><ShieldCheck size={14}/>Recibo v{brand.templateVersion??'2.0'}</span></div>
  {error&&<div className="error">{error}</div>}{message&&<div className="notice">{message}</div>}
  <section className={`cash-console ${session?'open':'closed'}`}><div className="cash-console-status"><span><Banknote size={25}/></span><div><small>Estado de caja</small><h2>{session?'Caja abierta':'Caja cerrada'}</h2><p>{session?`${session.location||'Punto de cobro'} · Apertura ${money(session.opening_amount)}`:'Abra una caja antes de recibir pagos en efectivo.'}</p></div></div>{session?<div className="cash-console-form"><label>Efectivo contado<input type="number" min="0" step="0.01" value={countedAmount} onChange={e=>setCountedAmount(e.target.value===''?'':Number(e.target.value))} placeholder="0.00"/></label><button className="outline" disabled={countedAmount===''} onClick={()=>void close()}>Cerrar y conciliar</button></div>:<div className="cash-console-form"><label>Fondo inicial<input type="number" min="0" step="0.01" value={openingAmount} onChange={e=>setOpeningAmount(Number(e.target.value))}/></label><label>Punto de cobro<input value={cashLocation} onChange={e=>setCashLocation(e.target.value)} placeholder="Secretaría"/></label><button disabled={!cashLocation.trim()} onClick={()=>void open()}>Abrir caja</button></div>}</section>

  <div className="payment-workflow"><div className={`workflow-step ${selected?'complete':'active'}`}><span>1</span><div><strong>Seleccionar abonado</strong><small>Buscar saldo pendiente.</small></div></div><div className={`workflow-step ${allocations.length?'complete':selected?'active':''}`}><span>2</span><div><strong>Elegir obligaciones</strong><small>Marcar conceptos a pagar.</small></div></div><div className={`workflow-step ${canConfirm?'active':''}`}><span>3</span><div><strong>Contabilizar</strong><small>Confirmar método y generar recibo.</small></div></div></div>

  <div className="search command-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Código, identidad o nombre del abonado" onKeyDown={e=>{if(e.key==='Enter')void search()}}/><button onClick={()=>void search()}><Search size={16}/>Buscar</button></div>
  <div className="payment-layout"><section className="panel payment-results"><div className="panel-heading"><div><h2>Abonados con saldo</h2><p>{results.length} resultado{results.length===1?'':'s'}</p></div></div>{results.map(result=><button className={`payment-account-card ${selected?.id===result.id?'active':''}`} key={result.id} onClick={()=>{setSelected(result);setChosen({});setReceived(0);setCashAmount(0)}}><span><strong>{result.full_name}</strong><small>{result.code}</small></span><b>{money(result.total_balance)}</b></button>)}{results.length===0&&<div className="empty-state"><WalletCards size={36}/><p>Busque un abonado para comenzar.</p></div>}</section>
   <section className="panel payment-entry"><div className="panel-heading"><div><h2>Documento de cobro</h2><p>{selected?`${selected.code} · ${selected.full_name}`:'Seleccione un abonado'}</p></div>{selected&&<span className="status-badge draft">Borrador</span>}</div>{selected?<><div className="table-scroll"><table><thead><tr><th>Aplicar</th><th>Concepto</th><th>Vencimiento</th><th>Saldo</th></tr></thead><tbody>{(selected.obligations??[]).map((obligation:Row)=><tr key={obligation.id}><td><input type="checkbox" checked={Boolean(chosen[obligation.id])} onChange={e=>setChosen({...chosen,[obligation.id]:e.target.checked})}/></td><td><strong>{obligation.description}</strong><small>{obligation.connection_code||'Obligación general'}</small></td><td>{obligation.due_date}</td><td>{money(obligation.balance)}</td></tr>)}</tbody></table></div><div className="payment-calculation"><div className="payment-fields"><label>Método<select value={method} onChange={e=>{const value=e.target.value as typeof method;setMethod(value);setReceived(value==='cash'?0:total);setCashAmount(0)}}><option value="cash">Efectivo</option><option value="transfer">Transferencia</option><option value="deposit">Depósito</option><option value="check">Cheque</option><option value="mixed">Mixto</option></select></label>{method!=='cash'&&method!=='mixed'&&<label>Referencia<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Número de operación"/></label>}{method==='mixed'&&<><label>Parte en efectivo<input type="number" min="0.01" max={Math.max(0,total-0.01)} step="0.01" value={cashAmount||''} onChange={e=>setCashAmount(Number(e.target.value))}/></label><label>Segundo método<select value={secondaryMethod} onChange={e=>setSecondaryMethod(e.target.value as typeof secondaryMethod)}><option value="transfer">Transferencia</option><option value="deposit">Depósito</option><option value="check">Cheque</option></select></label><label>Parte no efectiva<input readOnly value={secondaryAmount.toFixed(2)}/></label><label>Referencia no efectiva<input value={secondaryReference} onChange={e=>setSecondaryReference(e.target.value)}/></label></>}{requiresCash&&<label>Efectivo entregado<input type="number" min={method==='mixed'?cashAmount:total} step="0.01" value={received||''} onChange={e=>setReceived(Number(e.target.value))}/></label>}</div><aside className="payment-summary"><small>Total seleccionado</small><strong>{money(total)}</strong><div><span>Recibido</span><b>{money(effectiveReceived)}</b></div><div><span>Cambio</span><b>{money(Math.max(0,effectiveReceived-total))}</b></div><div><span>Método</span><b>{methodLabels[method]}</b></div><button disabled={!canConfirm} onClick={()=>void pay()}><CheckCircle2 size={18}/>Contabilizar y emitir recibo</button></aside></div></>:<div className="empty-state tall"><ReceiptText size={46}/><h3>Sin documento en proceso</h3><p>Seleccione un abonado y sus obligaciones.</p></div>}</section>
  </div>

  <section className="panel recent-payments"><div className="panel-heading"><div><h2>Pagos recientes</h2><p>Recibos, reimpresiones y movimientos de reverso.</p></div></div><div className="table-scroll"><table><thead><tr><th>Recibo</th><th>Abonado</th><th>Fecha</th><th>Método</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{payments.map(payment=><tr key={payment.id}><td><strong>{payment.receipt_number}</strong></td><td>{payment.subscriber_name}</td><td>{new Date(payment.created_at).toLocaleString('es-HN')}</td><td>{methodLabels[payment.method]??payment.method}</td><td>{money(payment.total)}</td><td><span className={`status-badge ${payment.status==='confirmed'?'approved':'critical'}`}>{payment.status==='confirmed'?'Pagado':payment.status}</span></td><td><div className="icon-actions">{payment.receipt_path&&<button className="icon-action-button" title="Reimprimir recibo" aria-label={`Reimprimir ${payment.receipt_number}`} onClick={()=>void reprintReceipt(payment)}><FileDown size={16}/></button>}{payment.receipt_path&&auth.has('communications.send')&&<button className="icon-action-button" title="Enviar por correo" aria-label={`Enviar ${payment.receipt_number} por correo`} onClick={()=>void emailReceipt(payment)}><Mail size={16}/></button>}{auth.has('payments.void')&&payment.status==='confirmed'&&<><button className="icon-action-button warning" title="Registrar devolución" onClick={()=>setAction({type:'refund',payment})}><RotateCcw size={16}/></button><button className="icon-action-button danger" title="Anular pago" onClick={()=>setAction({type:'void',payment})}><Ban size={16}/></button></>}</div></td></tr>)}</tbody></table></div></section>

  {action&&<div className="modal"><div className="modal-card"><div className="titlebar"><div><h2>{action.type==='void'?'Anular pago':'Registrar devolución'}</h2><p>Documento original: {action.payment.receipt_number}</p></div><button className="outline" onClick={()=>setAction(null)}><X size={17}/>Cerrar</button></div><div className="warning-box"><ShieldCheck size={20}/><p>El documento original no se eliminará. El sistema generará el movimiento de reverso correspondiente.</p></div>{action.type==='refund'&&<label>Monto a devolver<input type="number" min="0.01" max={Number(action.payment.total)} step="0.01" value={refundAmount||''} onChange={e=>setRefundAmount(Number(e.target.value))}/></label>}<label>Motivo obligatorio<textarea value={actionReason} onChange={e=>setActionReason(e.target.value)} placeholder="Explique el motivo con al menos 15 caracteres."/></label><button disabled={actionReason.trim().length<15||(action.type==='refund'&&(refundAmount<=0||refundAmount>Number(action.payment.total)))} onClick={()=>void confirmAction()}>{action.type==='void'?<><Ban size={17}/>Contabilizar anulación</>:<><RotateCcw size={17}/>Contabilizar devolución</>}</button></div></div>}
 </main>;
}
