import {useEffect,useMemo,useState} from 'react';
import {BadgeCheck,Camera,IdCard,KeyRound,LogOut,Mail,MapPin,Phone,Save,ShieldCheck,WalletCards,Waves} from 'lucide-react';
import {useAuth} from '../contexts/AuthContext';
import {changePortalPassword,getPortalProfile,updatePortalPhoto,updatePortalProfile} from '../features/portal/service';

type Row=Record<string,any>;
const money=(value:unknown)=>new Intl.NumberFormat('es-HN',{style:'currency',currency:'HNL'}).format(Number(value??0));
const initials=(name='')=>name.split(/\s+/).filter(Boolean).slice(0,2).map(value=>value[0]).join('').toUpperCase()||'AB';

export function SubscriberPortal(){
 const auth=useAuth();const[profile,setProfile]=useState<Row|null>(null);const[form,setForm]=useState({whatsapp:'',email:'',address:''});const[password,setPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(true);
 const mustChangePassword=Boolean(auth.portalState?.must_change_password);
 async function load(){setLoading(true);try{const data=await getPortalProfile();setProfile(data);setForm({whatsapp:data.whatsapp??'',email:data.email??'',address:data.address??''});setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const activeBenefits=useMemo(()=>(profile?.benefits??[]).filter((benefit:Row)=>benefit.status==='active'),[profile]);
 async function saveProfile(){if(mustChangePassword){setError('Debe cambiar su contraseña temporal antes de actualizar datos.');return;}try{await updatePortalProfile(form);setMessage('Datos de contacto actualizados correctamente.');await load()}catch(e){setError((e as Error).message)}}
 async function uploadPhoto(file?:File){if(!file)return;if(mustChangePassword){setError('Debe cambiar su contraseña temporal antes de actualizar fotografía.');return;}try{await updatePortalPhoto(file);setMessage('Fotografía actualizada correctamente.');await load()}catch(e){setError((e as Error).message)}}
 async function savePassword(){if(password!==confirmPassword){setError('Las contraseñas no coinciden.');return;}try{await changePortalPassword(password);setPassword('');setConfirmPassword('');setMessage('Contraseña actualizada correctamente.');await auth.refresh()}catch(e){setError((e as Error).message)}}
 if(loading)return <main className="portal-shell"><div className="portal-loading">Cargando expediente…</div></main>;
 return <main className="portal-shell">
  <header className="portal-header"><div className="portal-header-brand"><span><Waves size={24}/></span><div><strong>Junta Patronal de Agua Potable</strong><small>El Achiotal</small></div></div><button className="outline" onClick={()=>void auth.signOut()}><LogOut size={17}/>Cerrar sesión</button></header>
  <div className="portal-content">{error&&<div className="error">{error}</div>}{message&&<div className="notice">{message}</div>}
   {mustChangePassword&&<section className="portal-password-warning"><ShieldCheck size={28}/><div><h2>Debe cambiar su contraseña temporal</h2><p>Defina una contraseña personal antes de continuar usando el portal.</p></div><div className="portal-password-fields"><input type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Nueva contraseña"/><input type="password" minLength={10} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Confirmar contraseña"/><button disabled={password.length<10||confirmPassword.length<10} onClick={()=>void savePassword()}><KeyRound size={17}/>Cambiar contraseña</button></div></section>}
   {mustChangePassword&&<section className="portal-panel"><div className="portal-locked-fields"><ShieldCheck size={17}/><p>Por seguridad, el expediente, pagos, pegues y edición de fotografía quedan bloqueados hasta cambiar la contraseña temporal.</p></div></section>}
   {profile&&!mustChangePassword&&<><section className="portal-profile-card"><div className="portal-photo">{profile.photo_url?<img src={profile.photo_url} alt={`Fotografía de ${profile.full_name}`}/>:<span>{initials(profile.full_name)}</span>}<label title="Tomar o subir fotografía"><Camera size={17}/><input type="file" accept="image/jpeg,image/png,image/webp" capture="user" onChange={e=>{void uploadPhoto(e.target.files?.[0]);e.currentTarget.value=''}}/></label></div><div className="portal-profile-main"><span className="eyebrow">Mi ficha de abonado</span><h1>{profile.full_name}</h1><p>{profile.code} · {profile.identity_masked||'Identidad protegida'}</p><div className="portal-badges"><span><BadgeCheck size={14}/>{profile.status==='active'?'Servicio activo':profile.status}</span>{activeBenefits.map((benefit:Row,index:number)=><span key={`${benefit.name}-${index}`}>{benefit.name} · {benefit.percentage}%</span>)}</div></div></section>
   <div className="portal-grid"><section className="portal-panel"><div className="portal-panel-title"><div><h2>Mis datos de contacto</h2><p>Puede actualizar únicamente celular, correo y dirección.</p></div><ShieldCheck size={20}/></div><div className="portal-form"><label><Phone size={16}/>Número de celular<input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></label><label><Mail size={16}/>Correo electrónico<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="span-2"><MapPin size={16}/>Dirección<textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div><button onClick={()=>void saveProfile()}><Save size={17}/>Guardar mis datos</button><div className="portal-locked-fields"><IdCard size={17}/><p>Nombre, DNI, fecha de nacimiento, pegues, tarifas, pagos y estados solo pueden ser modificados por la Junta.</p></div></section>
   <section className="portal-panel"><div className="portal-panel-title"><div><h2>Mis pegues</h2><p>Conexiones registradas a su nombre.</p></div><MapPin size={20}/></div><div className="portal-connection-list">{(profile.connections??[]).map((connection:Row)=><article key={connection.id}><div><strong>{connection.code}</strong><span className={`status-badge ${connection.status==='active'?'approved':'draft'}`}>{connection.status}</span></div><p>{connection.address||'Dirección pendiente'}</p><small>{connection.sector||'Sector no definido'}</small></article>)}</div></section>
   <section className="portal-panel span-2"><div className="portal-panel-title"><div><h2>Estado anual</h2><p>Resumen de cuotas y saldos registrados.</p></div><WalletCards size={20}/></div><div className="portal-year-grid">{(profile.annual_status??[]).slice(0,8).map((year:Row,index:number)=><article key={`${year.year}-${index}`}><span>{year.year}</span><strong>{year.status==='paid'?'Pagado':year.status==='overdue'?'Vencido':'Pendiente'}</strong><b>{money(year.balance)}</b></article>)}{(profile.annual_status??[]).length===0&&<p className="empty">No existen anualidades registradas.</p>}</div></section></div></>}
  </div>
 </main>;
}
