import {useCallback,useEffect,useMemo,useState} from 'react';
import {BadgeCheck,LockKeyhole,Shield,UserPlus,UsersRound} from 'lucide-react';
import {inviteUser,listRoles,listUsers,setUserStatus} from '../features/users/service';
type Row=Record<string,any>;

export function Users(){
 const[users,setUsers]=useState<Row[]>([]);const[roles,setRoles]=useState<Row[]>([]);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const[form,setForm]=useState({email:'',full_name:'',username:'',role_id:''});
 const load=useCallback(async()=>{try{setUsers(await listUsers());setRoles(await listRoles());setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{void load()},[load]);
 const stats=useMemo(()=>({active:users.filter(user=>user.status==='active').length,blocked:users.filter(user=>user.status==='blocked').length,total:users.length}),[users]);
 async function submit(e:React.FormEvent){e.preventDefault();try{await inviteUser(form);setMessage('Invitación enviada. La persona deberá definir su contraseña y activar TOTP.');setForm({email:'',full_name:'',username:'',role_id:''});await load()}catch(err){setError((err as Error).message)}}
 async function changeStatus(user:Row,status:'active'|'inactive'|'blocked'){try{await setUserStatus(user.id,status);setMessage(`Estado de ${user.full_name} actualizado.`);await load()}catch(e){setError((e as Error).message)}}
 return <main className="content">
  <div className="titlebar"><div><h1>Usuarios y control de acceso</h1><p>Cuentas individuales, roles, MFA y protección especial del administrador principal.</p></div></div>
  {error&&<div className="error">{error}</div>}{message&&<div className="notice">{message}</div>}
  <div className="cards user-stats"><article><UsersRound size={20}/><small>Usuarios</small><h3>{stats.total}</h3></article><article><BadgeCheck size={20}/><small>Activos</small><h3>{stats.active}</h3></article><article><LockKeyhole size={20}/><small>Bloqueados</small><h3>{stats.blocked}</h3></article></div>
  <div className="subscriber-layout">
   <section className="panel"><h2>Usuarios registrados</h2><div className="table-scroll"><table><thead><tr><th>Nombre</th><th>Usuario</th><th>Rol</th><th>Estado</th><th>Control</th></tr></thead><tbody>{users.map(user=>{const superadmin=(user.roles??[]).some((role:Row)=>role.code==='superadmin');return <tr key={user.id}><td><strong>{user.full_name}</strong><small>{superadmin?'Cuenta maestra protegida':'Cuenta interna'}</small></td><td>{user.username}</td><td>{(user.roles??[]).map((role:Row)=><span className="role-chip" key={role.id}><Shield size={13}/>{role.name}</span>)}</td><td><span className={`status-badge ${user.status==='active'?'approved':user.status==='blocked'?'critical':'draft'}`}>{user.status==='active'?'Activo':user.status==='blocked'?'Bloqueado':'Inactivo'}</span></td><td>{superadmin?<div className="protected-admin"><LockKeyhole size={16}/><span>Siempre activo</span></div>:<div className="segmented-control"><button className={user.status==='active'?'selected':''} title="Activar" aria-label={`Activar ${user.full_name}`} onClick={()=>void changeStatus(user,'active')}><BadgeCheck size={16}/></button><button className={user.status==='inactive'?'selected':''} title="Inactivar" aria-label={`Inactivar ${user.full_name}`} onClick={()=>void changeStatus(user,'inactive')}><span>—</span></button><button className={user.status==='blocked'?'selected danger':''} title="Bloquear" aria-label={`Bloquear ${user.full_name}`} onClick={()=>void changeStatus(user,'blocked')}><LockKeyhole size={16}/></button></div>}</td></tr>})}</tbody></table></div></section>
   <section className="panel"><h2><UserPlus size={20}/> Crear usuario interno</h2><p className="help">El sistema enviará una invitación. No comparta contraseñas ni cree cuentas colectivas.</p><form className="subform" onSubmit={submit}><label>Nombre completo<input required minLength={3} value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Correo<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Nombre de usuario<input required minLength={3} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Rol<select required value={form.role_id} onChange={e=>setForm({...form,role_id:e.target.value})}><option value="">Seleccione un rol</option>{roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select></label><button><UserPlus size={17}/>Enviar invitación segura</button></form></section>
  </div>
 </main>;
}
