import { supabase } from '../../lib/supabase';
import type { AnnualGenerationInput,TariffInput } from './validation';
function db(){if(!supabase)throw new Error('La base segura aún no está configurada.');return supabase;}
function friendly(message:string){const map:Record<string,string>={FORBIDDEN:'No tiene permiso para realizar esta acción.',MFA_REQUIRED:'Debe verificar el segundo factor.',DUPLICATE_TARIFF_CODE:'Ya existe una tarifa con ese código.',VERSION_DATE_MUST_ADVANCE:'La nueva vigencia debe comenzar después de la versión anterior.',ANNUAL_TARIFF_NOT_FOUND:'La tarifa anual no existe o está inactiva.',NO_TARIFF_VERSION_FOR_YEAR:'No existe una versión vigente para ese año.',INVALID_YEAR:'El año indicado no es válido.'};return map[message]??message;}
export async function listTariffs(){const {data,error}=await db().rpc('list_tariffs');if(error)throw new Error(friendly(error.message));return data??[];}
export async function createTariff(input:TariffInput){const {data,error}=await db().rpc('create_tariff',{p_payload:input});if(error)throw new Error(friendly(error.message));return data;}
export async function createTariffVersion(definitionId:string,input:{amount:number;valid_from:string;valid_to?:string;notes?:string}){const {data,error}=await db().rpc('create_tariff_version',{p_definition_id:definitionId,p_payload:input});if(error)throw new Error(friendly(error.message));return data;}
export async function generateAnnualObligations(input:AnnualGenerationInput){const {data,error}=await db().rpc('generate_annual_obligations',{p_tariff_definition_id:input.tariff_definition_id,p_year:input.year,p_due_date:input.due_date});if(error)throw new Error(friendly(error.message));return data;}
export async function searchAccounts(query:string){const {data,error}=await db().rpc('search_subscriber_accounts',{p_query:query,p_limit:50});if(error)throw new Error(friendly(error.message));return data??[];}
export async function getSubscriberAccount(id:string){const {data,error}=await db().rpc('get_subscriber_account',{p_subscriber_id:id});if(error)throw new Error(friendly(error.message));return data;}
export async function checkDebtOperation(id:string,operation:string){const {data,error}=await db().rpc('check_debt_operation',{p_subscriber_id:id,p_operation:operation});if(error)throw new Error(friendly(error.message));return data;}

export async function createManualObligation(input:{subscriber_id:string;connection_id?:string;tariff_definition_id:string;due_date:string;description?:string}){const {data,error}=await db().rpc('create_manual_obligation',{p_subscriber_id:input.subscriber_id,p_connection_id:input.connection_id||null,p_tariff_definition_id:input.tariff_definition_id,p_due_date:input.due_date,p_description:input.description||null});if(error)throw new Error(friendly(error.message));return data;}
export async function authorizeDebtOverride(input:{subscriber_id:string;operation:string;reason:string}){const {data,error}=await db().rpc('authorize_debt_override',{p_subscriber_id:input.subscriber_id,p_operation:input.operation,p_reason:input.reason});if(error)throw new Error(friendly(error.message));return data;}
